apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: example-app-image
    newName: registry-nexus.apps.cluster.cjq7m.sandbox1718.opentlc.com/hello-world
    newTag: "latest"
